# Generated by Django 4.1.4 on 2022-12-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('stock', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
