# Generated by Django 4.1.4 on 2022-12-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projet', '0004_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('orders', models.ManyToManyField(to='app_projet.order')),
            ],
        ),
    ]
